
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 02 13:50:24 CET 2014
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 32;
  public static final int FUNCTION = 10;
  public static final int PUNTOYCOMA = 31;
  public static final int ENTERO = 42;
  public static final int INTEGER = 12;
  public static final int ARRAY = 3;
  public static final int OUT = 17;
  public static final int AND = 38;
  public static final int IS = 13;
  public static final int IGUALQUE = 36;
  public static final int MAYORQUE = 35;
  public static final int TYPE = 23;
  public static final int OR = 16;
  public static final int BEGIN = 4;
  public static final int LOOP = 14;
  public static final int IF = 11;
  public static final int COMILLASDOBLES = 25;
  public static final int INICIOCOMENTARIO = 28;
  public static final int ID = 41;
  public static final int PARENTESISIZQ = 26;
  public static final int OF = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 20;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int MENOS = 33;
  public static final int CONSTANT = 6;
  public static final int PUNTOPUNTO = 43;
  public static final int ASIGNACION = 39;
  public static final int PUTLINE = 19;
  public static final int MENORQUE = 34;
  public static final int ELSE = 7;
  public static final int PUNTO = 40;
  public static final int CARACTERESCADENA = 44;
  public static final int WHILE = 24;
  public static final int SALTOLINEA = 29;
  public static final int DISTINTOQUE = 37;
  public static final int THEN = 21;
  public static final int END = 8;
  public static final int PARENTESISDER = 27;
  public static final int FALSE = 9;
  public static final int PROCEDURE = 18;
  public static final int MAS = 2;
}

